DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS routines;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq START WITH 100000;

CREATE TABLE users
(
  id    INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  name  VARCHAR NOT NULL,
  email VARCHAR NOT NULL
);

CREATE TABLE routines
(
  id   INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
  name VARCHAR NOT NULL
)